# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nKHslRkswYomZnGn2ATFmDf8W8R8Shnk
"""

from flask import Flask, render_template, request

app = Flask(__name__)

# Function to calculate annuity
def calculate_annuity(starting_capital, interest_rate, periodic_payment, time_period):
    """
    Calculate the future value of an annuity.
    """
    # Convert annual interest rate to a periodic rate (assuming compounding annually)
    interest_rate = interest_rate / 100

    # Calculate the future value of periodic payments (ordinary annuity)
    future_value_payments = periodic_payment * (((1 + interest_rate) ** time_period - 1) / interest_rate)

    # Calculate the future value of the starting capital
    future_value_capital = starting_capital * ((1 + interest_rate) ** time_period)

    # Total future value of the annuity
    total_future_value = future_value_capital + future_value_payments

    return total_future_value

# Flask routes
@app.route('/')
def home():
    # Render the main input form
    return render_template('Annuity_Calc.html')

@app.route('/calculate', methods=['POST'])
def calculate():
    # Get form data
    starting_capital = float(request.form['starting_capital'])
    interest_rate = float(request.form['interest_rate'])
    periodic_payment = float(request.form['periodic_payment'])
    time_period = int(request.form['time_period'])

    # Calculate the future value
    future_value = calculate_annuity(starting_capital, interest_rate, periodic_payment, time_period)

    # Return the result to the user
    result = f"The total future value of the annuity is: ${future_value:.2f}"
    return render_template('Annuity_Calc.html', result=result)

if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    app.run(host="0.0.0.0", port=port)
